name: Update README

on:
  push:
    branches: [ "main" ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run README Update Script
        run: python scripts/update_checks_list.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are any changes
          if [[ -n $(git diff --exit-code) ]]; then
            git add README.md
            git add README.pypi.md
            git commit -m "Auto-update README [skip ci]"
            git push
          else
            echo "No changes to commit. Skipping commit and push."
          fi
